baseURL = "http://static.qapuas.id/"
languageCode = "en-us"
title = "Desa Delintas Karya"
theme = "godesa"

#HUGO_ENV="production" # production

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 
googleAnalytics = ""
enableRobotsTXT = true
Copyright = "Qapuas Static"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.header]]
    identifier = "header"
    name = "Kantor Sekretariat Desa"
    url = "/kantor-sekretariat-desa/"
  [[menu.header]]
    name = "Aspirasi Desa"
    url = "/aspirasi-desa/"

[params]
  favicon = "favicon.png"
  site_logo = "logo.png"
  description = "The last engine you'll ever need. Maybe."  
  facebook = "https://facebook.com/delintaskarya"
  twitter = "https://twitter.com/delintaskarya"
  instagram = ""
  youtube = ""
  github = "https://github.com/bernadussr/godesa"
  rss = ""
  background_color_class = "bg-green"
  bg_slider1 = "/images/slides/dayak-01.jpg"
  bg_slider2 = "/images/slides/dayak-02.jpg"
  recent_posts_number = 3

  Desa = "Delintas Karya"
  Kecamatan = "Boyan Tanjung"
  Kabupaten = "Kapuas Hulu"
  alamat = "Jl . Lintas Boyan"
  notelp = "+6285751491545"
  email = "delintas.karya@gmail.com"
  Kodedesa = "61.06.01.2006"
  NamaKepalaDesa = "Bahariman"
  DescKepalaDesa = "Telah menjabat sebagai kepala desa selama 4 tahun."
  JumlahPenduduk = "690"
  Jumlah_KK = "209"
  Jumlah_siswa = "228"
  Jumlah_kegiatan = "53"
  Latitude = "0,3223"
  Longitude = "112,334"