baseURL = "http://static.qapuas.id/"
languageCode = "en-us"
title = "Desa Delintas Karya"
theme = "godesa"

#HUGO_ENV="production" # production

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 
googleAnalytics = ""
enableRobotsTXT = true
Copyright = "Qapuas Static"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.header]]
    identifier = "header"
    name = "Kantor Sekretariat Desa"
    url = "/kantor-sekretariat-desa/"
  [[menu.header]]
    name = "Aspirasi Desa"
    url = "/aspirasi-desa/"

[params]
  Desa = "Delintas Karya"
  Kecamatan = "Boyan Tanjung"
  Kabupaten = "Kapuas Hulu"
  Kodedesa = "61.06.01.2006"
  JumlahPenduduk = "690"
  Jumlah_KK = "209"
  Jumlah_siswa = "228"
  Jumlah_kegiatan = "53"
  favicon = "favicon.png"
  site_logo = "logo.png"
  description = "The last engine you'll ever need. Maybe."
  NamaKepalaDesa = "Bahariman"
  DescKepalaDesa = "Telah menjabat sebagai kepala desa selama 4 tahun."
  facebook = ""
  twitter = "https://twitter.com/delintaskarya"
  instagram = ""
  youtube = ""
  github = ""
  rss = ""
  background_color_class = "bg-green"
  bg_slider1 = "/images/slides/dayak-01.jpg"
  bg_slider2 = "/images/slides/dayak-02.jpg"
  recent_posts_number = 3